<a href="https://colab.research.google.com/github/DengChiung/kmuh20231206/blob/main/1121223_coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 變數(Variables)和 表⽰式 (Expressions)

## 表示式


In [1]:
print(3 + 5)
print(3 + (5 * 4))
print(3 ** 2)
print('Hello ' + 'World')

8
23
9
Hello World


## 變數指定
### 型別是動態的，會根據指定時的物件來決定型別
### 變數單純只是物件的名稱，並不會和記憶體綁在⼀起。
### e.q.和記憶體綁在⼀起的是物件，⽽不是物件名稱!

In [ ]:
a = 4 + 3
b = a * 4.5
c = (a+b)/2.5
e = 'Hello World'

# 資料型態
### 整數 int
### 浮點數 float
### 複數 complex
### 字串 str
### 字節 bytes
### 字節陣列 bytearray
### 串列 list
### 序對 tuple
### 集合 set
### 字典 dict


## 內建的數字型態 (numeric types) 共有三種
### 1. int整數 -> 100
### 2. float浮點數 ->123.45
### 3. complex複數 -> 3+4j


# 數學運算

In [ ]:
10/3

3.3333333333333335

In [ ]:
50*0.5

25.0

In [ ]:
10+3j-3j

(10+0j)

# Python所⽀援的特殊運算

In [ ]:
#次⽅: 2**10
2**10

1024

In [ ]:
#整商除法:
10//3

3

# 複數運算
## c.real	實部
## c.imag 虛部


In [ ]:
a=3+4j
b=2-5j
c=a*b
c

(26-7j)

In [ ]:
#c.real 實部
c.real

26.0

In [ ]:
#c.imag 虛部
c.imag

-7.0

# 序列型態(sequence types)  可進⾏以下的計算

In [ ]:
# 假設有以下的值
x = 3
s = [1, 2, 3, 4, 5]
t = [6, 7, 8]
n = 3
i = 2
j = 4
k = 2

In [ ]:
## 1. 判斷元素是否在序列中
# 判斷x是否在s中
result1 = x in s
print(result1)  # 輸出True

# 判斷x是否不在s中
result2 = x not in s
print(result2)  # 輸出False

## 2. 連接與重複序列
# 連接s與t
result3 = s + t
print(result3)  # 輸出[1, 2, 3, 4, 5, 6, 7, 8]

# 將s重複n次連接s本身
result4 = n * s
print(result4)  # 輸出[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

##3. 索引與子序列
# 取得索引值i的元素
result5 = s[i]
print(result5)  # 輸出3

# 取得索引值i到j的子序列
result6 = s[i:j]
print(result6)  # 輸出[3, 4]

# 取得索引值i到j，間隔k的子序列
result7 = s[i:j:k]
print(result7)  # 輸出[3, 5]

# 4. 回傳序列的相關資訊
# 回傳s的元素個數
result8 = len(s)
print(result8)  # 輸出5

# 回傳s中的最小值
result9 = min(s)
print(result9)  # 輸出1

# 回傳s中的最大值
result10 = max(s)
print(result10)  # 輸出5

#5. 其他操作
# 取得s中第一次出現i的索引值
result11 = s.index(i)
print(result11)  # 輸出2

# 累計s中i出現的個數
result12 = s.count(i)
print(result12)  # 輸出1

# 串列(list)

In [ ]:
list1=[1,2+0j,"three" ,4.0]  # 不同型態的資料可以被收集在同一個清單中
list1[0] #顯示list的第0個元素 (在電腦領域裡計數由零開始)
list1[1] #顯示list的第0個元素
list1[2] #顯示list的第0個元素

In [ ]:
#任意物件的串列
a = [2, 3, 4] # A list of integer
b = [2, 7, 3.5, “Hello”] # A mixed list
c = [] # An empty list
d = [2, [a, b]] # A list containing a list
e = a + b # Join two lists

#串列的操作
x = a[1] # Get 2nd element (0 is first)
y = b[1:3] # Return a sub-list
z =d[1][0][2] # Nested lists
b[0] = 42 # Change an element


# 串列(list)型態有以下的⽅法

In [ ]:
my_list = [1, 2, 3, 4, 5]
x = 3
i = 2

In [ ]:
# 將元素 x 附加到列表的最後
my_list.append(x)
print(my_list)  # 輸出 [1, 2, 3, 4, 5, 3]

# 將列表 x 的所有元素附加到列表的最後
my_list.extend([8, 9, 10])
print(my_list)  # 輸出 [1, 2, 3, 4, 5, 3, 8, 9, 10]

# 計算列表中元素 x 的出現次數
count_x = my_list.count(x)
print(count_x)  # 輸出 2 (因為 x=3 出現兩次)

# 回傳元素 x 在列表中的索引值
index_x = my_list.index(x)
print(index_x)  # 輸出 2 (x=3 在列表中的第三個位置)

# 將元素 x 插入到列表的索引值 i 的位置
my_list.insert(i, x)
print(my_list)  # 輸出 [1, 2, 3, 3, 4, 5, 3, 8, 9, 10]

# 移除並返回列表中索引值為 i 的元素
removed_element = my_list.pop(i)
print(removed_element)  # 輸出 3 (移除的元素)
print(my_list)  # 輸出 [1, 2, 3, 4, 5, 3, 8, 9, 10]

# 移除列表中第一個出現的元素 x
my_list.remove(x)
print(my_list)  # 輸出 [1, 2, 4, 5, 3, 8, 9, 10]

# 倒轉列表中元素的順序
my_list.reverse()
print(my_list)  # 輸出 [10, 9, 8, 3, 5, 4, 2, 1]

# 對列表中的元素進行排序
my_list.sort()
print(my_list)  # 輸出 [1, 2, 3, 4, 5, 8, 9, 10]

# 序對(tuple)

In [ ]:
#tuple
f = (2,3,4,5) # An empty tuple
g = () # An empty tuple
h = (2, [3,4], (10,11,12)) # A tuple containing mixed  objects

In [ ]:
#tuple的操作
x = f[1] # Element access. x = 3
y = f[1:3] # Slices. y = (3,4)
z = h[1][1] # Nesting. z = 4

# 內建集合型態	(set)

## 1. Set 的特性
## 2. Set 是 Python 中的一種集合型別，其元素是無序的，集合內不允許有重複的元素。
## 3. 在建立 Set 時，可以使用花括號 `{}` 或者 `set()` 建構函數。
## 4. Set 中的元素順序不影響判斷相等性，只關心是否包含相同的元素。

In [ ]:
# 舉例：
s1 = {1, 1, 1, 2, 2, 3, 3, 4, 5}
s2 = {15, 3, 1, 2, 4}

# 檢查兩個 Set 是否相等
print(s1 == s2)  # 輸出 True

# 以 set 類型的建構函數去除重複元素
S1 = set(s1)
S2 = set(s2)

# 顯示排序後的 Set
print(S1)  # 輸出 {1, 2, 3, 4, 5}
print(S2)  # 輸出 {1, 2, 3, 4, 5}

# Set 是可變型態，因此指定時會產生新的 ID
print(id(s1))  # 輸出 4367107912
print(id(s2))  # 輸出 4367109928

# 檢查兩個 Set 是否為同一個物件
print(s1 is s2)  # 輸出 False

# 集合型態物件相對應的⽅法

In [ ]:
# 定義兩個 Set
s1 = {1, 2, 3, 4, 5}
s2 = {3, 4, 5, 6, 7}

# 等於 s1 & s2，取得兩個 Set 的交集
intersection_result = s1.intersection(s2)
print(intersection_result)  # 輸出 {3, 4, 5}

# 等於 s1 | s2，取得兩個 Set 的聯集
union_result = s1.union(s2)
print(union_result)  # 輸出 {1, 2, 3, 4, 5, 6, 7}

# 等於 s1 ^ s2，取得兩個 Set 的對稱差異
symmetric_difference_result = s1.symmetric_difference(s2)
print(symmetric_difference_result)  # 輸出 {1, 2, 6, 7}

# 等於 s1 - s2，取得 s1 中不在 s2 中的元素
difference_result = s1.difference(s2)
print(difference_result)  # 輸出 {1, 2}

# 等於 s1 <= s2，判斷 s1 是否為 s2 的子集
is_subset = s1.issubset(s2)
print(is_subset)  # 輸出 False

# 等於 s1 >= s2，判斷 s1 是否為 s2 的超集
is_superset = s1.issuperset(s2)
print(is_superset)  # 輸出 False

# 判斷 s1 與 s2 是否交集，若不交集則返回 True，否則返回 False
is_disjoint = s1.isdisjoint(s2)
print(is_disjoint)  # 輸出 False

# 回傳 s 的拷貝
s_copy = s1.copy()
print(s_copy)  # 輸出 {1, 2, 3, 4, 5}

# 由於 set 型態是可變的，因此有額外兩個新增與刪除元素的⽅法


In [ ]:
# 定義一個 Set
s = {1, 2, 3, 4, 5}

# 使用 add 方法增加元素
s.add(6)
print(s)  # 輸出 {1, 2, 3, 4, 5, 6}

# 使用 remove 方法刪除元素
s.remove(3)
print(s)  # 輸出 {1, 2, 4, 5, 6}

# 內建字典型態	(dict)

## 字典物件可進⾏的運算

In [ ]:
# 定義一個字典
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}

# 從字典中取得鍵 'name' 的值
value = my_dict['name']
print(f"Value for key 'name': {value}")

# 將字典中鍵 'age' 指定為值 35
my_dict['age'] = 35
print(f"Updated dictionary: {my_dict}")

# 刪除字典中鍵 'city' 及其值
del my_dict['city']
print(f"Dictionary after deleting key 'city': {my_dict}")

# 判斷鍵 'age' 是否在字典中
key_exists = 'age' in my_dict
print(f"Key 'age' exists in dictionary: {key_exists}")

# 判斷鍵 'city' 是否不在字典中
key_not_exists = 'city' not in my_dict
print(f"Key 'city' does not exist in dictionary: {key_not_exists}")

# 回傳由字典建立的迭代器
dict_iterator = iter(my_dict)
print(f"Dictionary iterator: {dict_iterator}")

# 回傳字典的配對資料個數
dict_length = len(my_dict)
print(f"Number of key-value pairs in dictionary: {dict_length}")

## 字典物件的⽅法	(method)

In [ ]:
# 定義一個字典
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}

# 清空字典的所有配對資料
my_dict.clear()
print(f"Dictionary after clear: {my_dict}")

# 複製字典
copied_dict = my_dict.copy()
print(f"Copied dictionary: {copied_dict}")

# 使用 fromkeys 創建新字典
seq = ['name', 'age', 'city']
new_dict = dict.fromkeys(seq, 'N/A')
print(f"New dictionary from keys: {new_dict}")

# 從字典中取得鍵 'name' 的值，若鍵不存在則回傳 None
name_value = my_dict.get('name')
print(f"Value for key 'name': {name_value}")

# 回傳字典 items 物件，使 key:value 儲存為序對
items_iterator = my_dict.items()
print(f"Dictionary items iterator: {items_iterator}")

# 回傳字典 keys 物件，使 key 依序儲存其中
keys_iterator = my_dict.keys()
print(f"Dictionary keys iterator: {keys_iterator}")

# 將 'age' 的 value 從字典移除，若 'age' 不存在則回傳 0
removed_value = my_dict.pop('age', 0)
print(f"Removed value for key 'age': {removed_value}")
print(f"Dictionary after pop: {my_dict}")

# 從字典移除任意一組 key:value 配對
removed_item = my_dict.popitem()
print(f"Removed item: {removed_item}")
print(f"Dictionary after popitem: {my_dict}")

# 如果 'gender' 在字典中，傳回其 value 值，否則將 'gender':'unknown' 加入字典
gender_value = my_dict.setdefault('gender', 'unknown')
print(f"Gender value: {gender_value}")
print(f"Dictionary after setdefault: {my_dict}")

# 將另一個字典中的配對資料更新到原字典
update_dict = {'city': 'Los Angeles', 'occupation': 'Engineer'}
my_dict.update(update_dict)
print(f"Updated dictionary: {my_dict}")

# 回傳字典 values 物件，使 value 依序儲存其中
values_iterator = my_dict.values()
print(f"Dictionary values iterator: {values_iterator}")


# 型態轉換

In [ ]:
# 1. 轉換成整數型態 (int)
num_str = "42"
num_int = int(num_str)
print(f"整數型態轉換結果：{num_int}")  # 輸出 42

# 2. 轉換成浮點數型態 (float)
float_str = "3.14"
float_num = float(float_str)
print(f"浮點數型態轉換結果：{float_num}")  # 輸出 3.14

# 3. 轉換成字串型態 (str)
num = 123
num_str = str(num)
print(f"字串型態轉換結果：'{num_str}'")  # 輸出 '123'

# 4. 轉換成列表型態 (list)
str_example = "hello"
list_example = list(str_example)
print(f"列表型態轉換結果：{list_example}")  # 輸出 ['h', 'e', 'l', 'l', 'o']

# 5. 轉換成元組型態 (tuple)
list_example = [1, 2, 3]
tuple_example = tuple(list_example)
print(f"元組型態轉換結果：{tuple_example}")  # 輸出 (1, 2, 3)

# 6. 轉換成布林型態 (bool)
num = 0
bool_example = bool(num)
print(f"布林型態轉換結果：{bool_example}")  # 輸出 False

# if/else 轉換

In [ ]:
#if 範例程式1
#判斷 2的10次方是否等於1024

if 2**10 == 1024:
    print("2^10=1024")

In [ ]:
#判斷輸入的數字是奇數還是偶數

num = int(input('Please input a num:'))

if num % 2 == 0:
    print(num,'是偶數')
else:
    print(num,'是奇數')

In [ ]:
#輸入兩個數字比大小

num1 = int(input('Please input a num1:'))
num2 = int(input('Please input a num2:'))

if num1 == num2:
    print(num1,'等於',num2)
elif num1 < num2:
    print(num1,'小於',num2)
else:
    print(num1,'大於',num2)

# 動動腦

In [ ]:
# 計算BMI並輸出分級值
#
# BMI = 體重 (kg) / 身高 (m^2)
'''
成人的體重分級與標準
分   級    身體質量指數
體重過輕    BMI ＜ 18.5
正常範圍    18.5 ≦ BMI ＜24
過   重    24 ≦ BMI ＜ 27
輕度肥胖    27 ≦ BMI ＜ 30
中度肥胖    30 ≦ BMI ＜ 35
重度肥胖    BMI ≧ 35
'''

height = int(input('Please input a height(cm):'))
weight = int(input('Please input a weight(kg):'))

BMI = weight / float(height/100)**2

print("BMI:",BMI)

if BMI < 18.5:
    print('體重過輕')
elif 18.5 <= BMI < 24:
    print('正常範圍')
elif 24 <= BMI < 27:
    print('過   重')
elif 27 <= BMI < 30:
    print('輕度肥胖')
elif 27 <= BMI < 30:
    print('輕度肥胖')
elif 30 <= BMI < 35:
    print('中度肥胖')
else:
    print('重度肥胖')

# For 迴圈

In [ ]:
# 輸入一個數字n，計算1+2+3+...+n的總和為多少?
# (for 迴圈版本)

n = int(input('Please input n:'))
total = 0

for i in range(1,n+1):
    # total += i  等價於 total = total + i
    total += i
print('Total is:',total)

# 動動腦

# 定義函式

In [ ]:
def summation(n):
    total = 0
    for i in range(1,n+1):
        # total += i  等價於 total = total + i
        total += i
    print('Total is:',total)

#函式宣告完之後才能呼叫
summation(100)

In [ ]:
#  函數的預設值為可變物件

def append_item(item, lis=[]):
    lis.append(item)
    return lis

print(append_item('apple'))
print(append_item('orange'))
print(append_item('peach'))

In [ ]:
#  全域變數範例
#

#name 變數宣告在最外層，為全域變數
name = "Tony"

def change_name(n):
    global name
    name = n
    print('In change_name function, name=%s' % name)

print('Before change_name function called, name=%s' % name)
change_name('John')
print('After change_name function called, name=%s' % name)

# Numpy

## 建立基本陣列

In [ ]:
import numpy as np
np1 = np.array([1,2,3,4])		#使用list
np2 = np.array((5,6,7,8))		#使用tuple
print(np1)
print(np2)
print(type(np1), type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [ ]:
import numpy as np
na = np.arange(0, 31, 2)
print(na)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [ ]:
import numpy as np
na = np.linspace(1, 15, 3)
print(na)

[ 1.  8. 15.]


In [ ]:
import numpy as np
a = np.zeros((5,))
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
b = np.ones((5,))
print(b)

[1. 1. 1. 1. 1.]


## 建立多維陣列

In [ ]:
import numpy as np
listdata = [[1,2,3,4,5],
       [6,7,8,9,10]]
na = np.array(listdata)
print(na)
print('維度', na.ndim)
print('形狀', na.shape)
print('數量', na.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
維度 2
形狀 (2, 5)
數量 10


## 改變陣列形狀：reshape()

In [ ]:
import numpy as np
adata = np.arange(1,17)
print(adata)
bdata = adata.reshape(4,4)
print(bdata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## 一維陣列取值

In [ ]:
import numpy as np
na = np.arange(0,6)
print(na)
print(na[0])
print(na[5])
print(na[1:5])
print(na[1:5:2])
print(na[5:1:-1])
print(na[:])
print(na[:3])
print(na[3:])

[0 1 2 3 4 5]
0
5
[1 2 3 4]
[1 3]
[5 4 3 2]
[0 1 2 3 4 5]
[0 1 2]
[3 4 5]


## 多維陣列取值

In [ ]:
import numpy as np
na = np.arange(1, 17).reshape(4, 4)
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
na[2, 3]

12

In [ ]:
print(na[1, 1:3])			#[6,7]
print(na[1:3, 2])			#[7,11]
print(na[1:3, 1:3])		#[[6,7],[7,11]]
print(na[::2, ::2])		#[[1,3],[9,11]]
print(na[:, 2])				#[3,7,11,15]
print(na[1, :])				#[5,6,7,8]
print(na[:, :])				#矩陣全部

[6 7]
[ 7 11]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]]
[ 3  7 11 15]
[5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## 產生隨機資料:np.ramdom()

In [ ]:
import numpy as np
print('1.產生2x3 0~1之間的隨機浮點數\n',
      np.random.rand(2,3))
print('2.產生2x3常態分佈的隨機浮點數\n',
      np.random.randn(2,3))
print('3.產生0~4(不含5)隨機整數\n',
      np.random.randint(5))
print('4.產生2~4(不含5)5個隨機整數\n',
      np.random.randint(2,5,[5]))
print('5.產生3個 0~1之間的隨機浮點數\n',
      np.random.random(3),'\n',
      np.random.random_sample(3),'\n',
      np.random.sample(3))

1.產生2x3 0~1之間的隨機浮點數
 [[0.06050003 0.93301425 0.71076991]
 [0.84010536 0.28689356 0.22762804]]
2.產生2x3常態分佈的隨機浮點數
 [[-1.17077405 -0.59738168 -0.10755275]
 [ 0.66430635 -0.35948383  0.47755052]]
3.產生0~4(不含5)隨機整數
 0
4.產生2~4(不含5)5個隨機整數
 [2 2 2 3 4]
5.產生3個 0~1之間的隨機浮點數
 [0.74134004 0.3726241  0.84656695] 
 [0.11238613 0.08427853 0.56516163] 
 [0.93530103 0.4546523  0.89867011]


## Numpy讀取CSV 檔案

In [ ]:
import numpy as np
na = np.genfromtxt('scores.csv', delimiter=',', skip_header=1)
print(na.shape)

(30, 4)


## Numpy陣列運算

In [ ]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print('a 陣列內容：\n', a)
print('b 陣列內容：\n', b)

a 陣列內容：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b 陣列內容：
 [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
print('a 陣列元素都加值：\n', a + 1)

a 陣列元素都加值：
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
print('a 陣列元素都平方：\n', a ** 2)

a 陣列元素都平方：
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
print('a 陣列元素加判斷：\n', a < 5)

a 陣列元素加判斷：
 [[ True  True  True]
 [ True False False]
 [False False False]]


In [ ]:
print('a 陣列取出第一個row都加1：\n', a[0,:] + 1)
print('a 陣列取出第一個col都加1：\n', a[:,0] + 1)

a 陣列取出第一個row都加1：
 [2 3 4]
a 陣列取出第一個col都加1：
 [2 5 8]


In [ ]:
print('a b 陣列對應元素相加：\n', a + b)
print('a b 陣列對應元素相乘：\n', a * b)

a b 陣列對應元素相加：
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
a b 陣列對應元素相乘：
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [ ]:
print('a b 陣列內積計算：\n', np.dot(a,b))

a b 陣列內積計算：
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


## Numpy常用的計算及統計函式

In [ ]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
print('陣列的內容：\n', a)
print('1.最小值與最大值：\n',
      np.min(a), np.max(a))
print('2.每一直行最小值與最大值：\n',
      np.min(a, axis=0), np.max(a, axis=0))
print('3.每一橫列最小值與最大值：\n',
      np.min(a, axis=1), np.max(a, axis=1))
print('4.加總、乘積及平均值：\n',
      np.sum(a), np.prod(a), np.mean(a))
print('5.每一直行加總、乘積與平均值：\n',
      np.sum(a, axis=0), np.prod(a, axis=0), np.mean(a, axis=0))
print('6.每一橫列加總、乘積與平均值：\n',
      np.sum(a, axis=1), np.prod(a, axis=1), np.mean(a, axis=1))

陣列的內容：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1.最小值與最大值：
 1 9
2.每一直行最小值與最大值：
 [1 2 3] [7 8 9]
3.每一橫列最小值與最大值：
 [1 4 7] [3 6 9]
4.加總、乘積及平均值：
 45 362880 5.0
5.每一直行加總、乘積與平均值：
 [12 15 18] [ 28  80 162] [4. 5. 6.]
6.每一橫列加總、乘積與平均值：
 [ 6 15 24] [  6 120 504] [2. 5. 8.]


In [ ]:
import numpy as np
a = np.random.randint(100,size=50)
print('陣列的內容：', a)
print('1.標準差：', np.std(a))
print('2.變異數：', np.var(a))
print('3.中位數：', np.median(a))
print('4.百分比值：', np.percentile(a, 80))
print('5.最大最小差值：', np.ptp(a))

陣列的內容： [56 30  3 80 50 86 70 25 60 46 88 47 10 59  1 72 64 15 92 78 56 44  5  4
 51 56 94 30 28 62 31 15 21 76 95 97 16 29 72 45 24 24 30 35 63 88 32 64
 40 46]
1.標準差： 27.08228203087768
2.變異數： 733.45
3.中位數： 46.5
4.百分比值： 72.80000000000001
5.最大最小差值： 96


## Numpy的排序

In [ ]:
import numpy as np
a = np.random.choice(50, size=10, replace=False)
print('排序前的陣列：', a)
print('排序後的陣列：', np.sort(a))
print('排序後的索引：', np.argsort(a))
#用索引到陣列取值
for i in np.argsort(a):
    print(a[i], end=',')

排序前的陣列： [ 6  3 20 25 27 24 17 28 23 29]
排序後的陣列： [ 3  6 17 20 23 24 25 27 28 29]
排序後的索引： [1 0 6 2 8 5 3 4 7 9]
3,6,17,20,23,24,25,27,28,29,

In [ ]:
import numpy as np
a = np.random.randint(0,10,(3,5))
print('原陣列內容：')
print(a)
print('將每一直行進行排序：')
print(np.sort(a, axis=0))
print('將每一橫列進行排序：')
print(np.sort(a, axis=1))

原陣列內容：
[[4 7 7 8 0]
 [8 0 2 2 5]
 [6 5 1 0 9]]
將每一直行進行排序：
[[4 0 1 0 0]
 [6 5 2 2 5]
 [8 7 7 8 9]]
將每一橫列進行排序：
[[0 4 7 7 8]
 [0 2 2 5 8]
 [0 1 5 6 9]]


# Pandas

In [ ]:
!pip install pandas

## 建立Series

In [ ]:
import pandas as pd
se = pd.Series([1,2,3,4,5])
print(se)           #顯示Series
print(se.values)    #顯示值
print(se.index)     #顯示索引

0    1
1    2
2    3
3    4
4    5
dtype: int64
[1 2 3 4 5]
RangeIndex(start=0, stop=5, step=1)


In [ ]:
import pandas as pd
dict1 = {'Taipei': '台北', 'Taichung': '台中', 'Kaohsiung': '高雄'}
se = pd.Series(dict1)
print(se)           #顯示Series
print(se.values)    #顯示值
print(se.index)     #顯示索引
print(se['Taipei']) #用索引取值

Taipei       台北
Taichung     台中
Kaohsiung    高雄
dtype: object
['台北' '台中' '高雄']
Index(['Taipei', 'Taichung', 'Kaohsiung'], dtype='object')
台北


In [ ]:
print(se['Taichung':'Kaohsiung'])

Taichung     台中
Kaohsiung    高雄
dtype: object


## Series資料取值

In [ ]:
import pandas as pd
se = pd.Series([1,2,3,4,5])
se[2]

3

In [ ]:
import pandas as pd
se = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
se['b']

2

## 建立DataFrame

In [ ]:
import pandas as pd
df = pd.DataFrame([[65,92,78,83,70],
                   [90,72,76,93,56],
                   [81,85,91,89,77],
                   [79,53,47,94,80]])
df

0   1   2   3   4
0  65  92  78  83  70
1  90  72  76  93  56
2  81  85  91  89  77
3  79  53  47  94  80

In [ ]:
import pandas as pd
df = pd.DataFrame([[65,92,78,83,70],
                   [90,72,76,93,56],
                   [81,85,91,89,77],
                   [79,53,47,94,80]],
                   index=['王小明','李小美','陳大同','林小玉'],
                   columns=['國文','英文','數學','自然','社會'])
df

國文  英文  數學  自然  社會
王小明  65  92  78  83  70
李小美  90  72  76  93  56
陳大同  81  85  91  89  77
林小玉  79  53  47  94  80

## 利用字典建立DataFrame

In [ ]:
import pandas as pd
scores = {'國文':{'王小明':65,'李小美':90,'陳大同':81,'林小玉':79},
          '英文':{'王小明':92,'李小美':72,'陳大同':85,'林小玉':53},
          '數學':{'王小明':78,'李小美':76,'陳大同':91,'林小玉':47},
          '自然':{'王小明':83,'李小美':93,'陳大同':89,'林小玉':94},
          '社會':{'王小明':70,'李小美':56,'陳大同':94,'林小玉':80}}
df = pd.DataFrame(scores)
df

國文  英文  數學  自然  社會
王小明  65  92  78  83  70
李小美  90  72  76  93  56
陳大同  81  85  91  89  94
林小玉  79  53  47  94  80

## 利用Series建立DataFrame

In [ ]:
import pandas as pd
se1 = pd.Series({'王小明':65,'李小美':90,'陳大同':81,'林小玉':79})
se2 = pd.Series({'王小明':92,'李小美':72,'陳大同':85,'林小玉':53})
se3 = pd.Series({'王小明':78,'李小美':76,'陳大同':91,'林小玉':47})
se4 = pd.Series({'王小明':83,'李小美':93,'陳大同':89,'林小玉':94})
se5 = pd.Series({'王小明':70,'李小美':56,'陳大同':94,'林小玉':80})
df = pd.DataFrame({ '國文':se1,'英文':se2,'數學':se3,
                   '自然':se4,'社會':se5} )
df

國文  英文  數學  自然  社會
王小明  65  92  78  83  70
李小美  90  72  76  93  56
陳大同  81  85  91  89  94
林小玉  79  53  47  94  80

In [ ]:
import pandas as pd
se1 = pd.Series({'王小明':65,'李小美':90,'陳大同':81,'林小玉':79})
se2 = pd.Series({'王小明':92,'李小美':72,'陳大同':85,'林小玉':53})
se3 = pd.Series({'王小明':78,'李小美':76,'陳大同':91,'林小玉':47})
se4 = pd.Series({'王小明':83,'李小美':93,'陳大同':89,'林小玉':94})
se5 = pd.Series({'王小明':70,'李小美':56,'陳大同':94,'林小玉':80})
df = pd.concat([se1,se2,se3,se4,se5], axis=1)
df.columns=['國文','英文','數學','自然','社會']
df

國文  英文  數學  自然  社會
王小明  65  92  78  83  70
李小美  90  72  76  93  56
陳大同  81  85  91  89  94
林小玉  79  53  47  94  80

## DataFrame基本取值

In [ ]:
df["自然"]

王小明    83
李小美    93
陳大同    89
林小玉    94
Name: 自然, dtype: int64

In [ ]:
df[["國文", "數學", "自然"]]

國文  數學  自然
王小明  65  78  83
李小美  90  76  93
陳大同  81  91  89
林小玉  79  47  94

In [ ]:
df[df["國文"] >= 80]

國文  英文  數學  自然  社會
李小美  90  72  76  93  56
陳大同  81  85  91  89  94

In [ ]:
df.values

array([[65, 92, 78, 83, 70],
       [90, 72, 76, 93, 56],
       [81, 85, 91, 89, 94],
       [79, 53, 47, 94, 80]])

In [ ]:
df.values[1]

array([90, 72, 76, 93, 56])

In [ ]:
df.values[1][2]

76

## 以索引及欄位名稱取得資料：df.loc()

In [ ]:
df.loc["林小玉", "社會"]

80

In [ ]:
df.loc["王小明", ["國文","社會"]]

國文    65
社會    70
Name: 王小明, dtype: int64

In [ ]:
df.loc[["王小明", "李小美"], ["數學", "自然"]]

數學  自然
王小明  78  83
李小美  76  93

In [ ]:
df.loc["王小明":"陳大同", "數學":"社會"]

數學  自然  社會
王小明  78  83  70
李小美  76  93  56
陳大同  91  89  94

In [ ]:
df.loc["陳大同", :]

國文    81
英文    85
數學    91
自然    89
社會    94
Name: 陳大同, dtype: int64

In [ ]:
df.loc[:"李小美", "數學":"社會"]

數學  自然  社會
王小明  78  83  70
李小美  76  93  56

In [ ]:
df.loc["李小美":, "數學":"社會"]

數學  自然  社會
李小美  76  93  56
陳大同  91  89  94
林小玉  47  94  80

## 以索引及欄位編號取得資料：df.iloc()

In [ ]:
df.iloc[3, 4]

80

In [ ]:
df.iloc[0, [0, 4]]

國文    65
社會    70
Name: 王小明, dtype: int64

In [ ]:
df.iloc[[0, 1], [2, 3]]

數學  自然
王小明  78  83
李小美  76  93

In [ ]:
df.iloc[0:3, 2:5]

數學  自然  社會
王小明  78  83  70
李小美  76  93  56
陳大同  91  89  94

In [ ]:
df.iloc[2, :]

國文    81
英文    85
數學    91
自然    89
社會    94
Name: 陳大同, dtype: int64

In [ ]:
df.iloc[:2, 2:5]

數學  自然  社會
王小明  78  83  70
李小美  76  93  56

In [ ]:
df.iloc[1:, 2:5]

數學  自然  社會
李小美  76  93  56
陳大同  91  89  94
林小玉  47  94  80

## 取得最前或最後幾列資料

In [ ]:
df.head(2)

國文  英文  數學  自然  社會
王小明  65  92  78  83  70
李小美  90  72  76  93  56

In [ ]:
df.tail(2)

國文  英文  數學  自然  社會
陳大同  81  85  91  89  94
林小玉  79  53  47  94  80

## DataFrame資料排序

In [ ]:
df.sort_values(by="數學", ascending=False)

國文  英文  數學  自然  社會
陳大同  81  85  91  89  94
王小明  65  92  78  83  70
李小美  90  72  76  93  56
林小玉  79  53  47  94  80

In [ ]:
df.sort_index(axis=0)

國文  英文  數學  自然  社會
李小美  90  72  76  93  56
林小玉  79  53  47  94  80
王小明  65  92  78  83  70
陳大同  81  85  91  89  94

## DataFrame資料修改

In [ ]:
df.loc["王小明"]["數學"] = 90
df

國文  英文  數學  自然  社會
王小明  65  92  90  83  70
李小美  90  72  76  93  56
陳大同  81  85  91  89  94
林小玉  79  53  47  94  80

In [ ]:
df.loc["王小明", :] = 80
df

國文  英文  數學  自然  社會
王小明  80  80  80  80  80
李小美  90  72  76  93  56
陳大同  81  85  91  89  94
林小玉  79  53  47  94  80

## 刪除DataFrame資料

In [ ]:
df.drop("王小明")

國文  英文  數學  自然  社會
李小美  90  72  76  93  56
陳大同  81  85  91  89  94
林小玉  79  53  47  94  80

In [ ]:
df.drop("數學", axis=1)

國文  英文  自然  社會
王小明  80  80  80  80
李小美  90  72  93  56
陳大同  81  85  89  94
林小玉  79  53  94  80

In [ ]:
df.drop(["數學", "自然"], axis=1)

國文  英文  社會
王小明  80  80  80
李小美  90  72  56
陳大同  81  85  94
林小玉  79  53  80

In [ ]:
df.drop(df.index[1:4])

國文  英文  數學  自然  社會
王小明  80  80  80  80  80

In [ ]:
df.drop(df.columns[1:4], axis=1)

# 資料前處理

In [ ]:
# 讀取資料
import pandas as pd
df = pd.read_excel("提供資料_學員.xlsx")

TypeError: read_excel() missing 1 required positional argument: 'io'

In [ ]:
# 查看資料總筆數
print(len(df))

In [ ]:
# 查看欄位數量
len(df.columns)

In [ ]:
# 查看資料型態
data_types = df.dtypes

# 印出結果
print(data_types)

In [ ]:
#每個欄位的缺失值數量
#使用 isnull() 函數結合 sum() 函數
# 查看缺失值數量
missing_values = df.isnull().sum()

# 印出結果
print(missing_values)

# 清理缺失值


In [ ]:
#針對 Survival 欄位找出異常的資料並移除
# 移除Survival欄位異常值
df = df[df['Survival'].isin([0, 1])]

# 印出結果
print("移除Survival欄位異常值後的資料：")
print(df)

In [ ]:
#針對 Age 進行篩選，找出年齡在 18 到 80 歲之間的病人
filtered_age = df[(df['AGE'] >= 18) & (df['AGE'] <= 80)]

# 印出篩選後的結果
print("篩選後的年齡資料：")
print(filtered_age)

# 補值

## 平均值補值（Mean Imputation）：使用該欄位的平均值填補缺失值。

In [ ]:
df[['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']] = df[['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']].fillna(df[['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']].mean())

### 中位數補值（Median Imputation）：使用該欄位的中位數填補缺失值。

In [ ]:
df[['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']] = df[['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']].fillna(df[['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']].median())

### 前後值補值（Forward Fill / Backward Fill）：使用缺失值前面或後面的值填補。

In [ ]:
df[['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']] = df[['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']].fillna(method='ffill')  # Forward Fill
# 或
df[['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']] = df[['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']].fillna(method='bfill')  # Backward Fill

### 插值法補值（Interpolation）：使用相鄰值的插值填補。

In [ ]:
df[['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']] = df[['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']].interpolate(method='linear')

### 使用固定範圍的隨機值進行補值
### 針對每個欄位生成位於指定範圍內的隨機值，並將這些值填入相應欄位的缺失值位置。
### 根據需求調整 lower_bound 和 upper_bound 的值

In [ ]:
import numpy as np

# 定義補值的範圍
lower_bound = 50  # 你的下限
upper_bound = 100  # 你的上限

# 針對 HR、NBPs、NBPd、T、RR、SpO2 欄位進行補值
columns_to_impute = ['HR', 'NBPs', 'NBPd', 'T', 'RR', 'SpO2']

for column in columns_to_impute:
    # 產生隨機值
    random_values = np.random.uniform(lower_bound, upper_bound, size=df[column].isnull().sum())

    # 將隨機值填入缺失值的位置
    df.loc[df[column].isnull(), column] = random_values

### df['Sex']的資料型態是字串或類別型態

In [ ]:
# 將性別欄位中的M轉換為0，F轉換為1
df['Sex'] = df['Sex'].map({'M': 0, 'F': 1})

## 混合格式欄位處理

In [ ]:
#使用pd.to_numeric函式將"Sugar"欄位轉換為數值，同時將無法轉換的非數值部分替換為NaN
# 將非數值的值取代為NaN
df['Sugar'] = pd.to_numeric(df['Sugar'], errors='coerce')

# 印出處理後的資料
print("\n排除非數值的欄位後:")
print(df)

## 資料轉換 Data Transformation

In [ ]:
# 資料轉換示例：使用PCA進行降維
from sklearn.decomposition import PCA

# 假設df是包含原始資料的DataFrame
features = df[['Sugar', 'WBC']]

# 初始化PCA模型，指定要降至的維度
pca = PCA(n_components=2)

# 將原始資料轉換成降維後的資料
transformed_data = pca.fit_transform(features)

# 將降維後的資料加入原始DataFrame
df[['PCA1', 'PCA2']] = transformed_data

# 減少資料量 Data Reduction

In [ ]:
# 減少資料量示例：使用隨機抽樣
# 假設df是包含原始資料的DataFrame
sampled_data = df.sample(frac=0.5, random_state=42)

# 資料離散化 Data Discretization

In [ ]:
# 資料離散化示例：使用pandas的cut函式
# 假設df是包含原始資料的DataFrame
df['discretized_feature'] = pd.cut(df['Sugar'], bins=5, labels=False)

# 清理文本並將其轉換為數值

In [ ]:
# 假設df是包含原始資料的DataFrame
# 假設"Sugar"欄位中包含非數值字元，我們要先清理這些字元
df['Sugar'] = df['Sugar'].replace('[^\d.]', '', regex=True)

# 使用pd.to_numeric將清理後的"Sugar"欄位轉換為數值
df['Sugar'] = pd.to_numeric(df['Sugar'], errors='coerce')

In [ ]:
## df['婚姻'].unique()